### ISSUE TITLE
Not able to retrieve image

### ISSUE THREAD

**Issue by mikadev** [VirtusLab-Open-Source/strapi-plugin-navigation#239]
It is currently not possible to retrieve media (image field)

**Strapi call with populate result**
![image](https://user-images.githubusercontent.com/3314041/175261765-f08a52e5-dbc5-48a2-87e3-7be7c9841bde.png)
  
  
**Ui navigation call without image attribute**
![image](https://user-images.githubusercontent.com/3314041/175263068-a622648b-acd0-4cf1-8f73-147d19506bf6.png)

Please add ability to use [populate query param from strapi](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#population) or something similar will allow us to get every related object thanks

**Comment by cyp3rius** [comment]
@mikadev checking the url you're using seems not our plugin ;) Are you sure you're referring to the right one?

**Comment by mikadev** [comment]
> @mikadev checking the url you're using seems not our plugin ;) Are you sure you're referring to the right one?

I update the ticket the first call is just a strapi call with populate parameter

**Comment by cyp3rius** [comment]
Have you set proper fields to population in `Settings -> Navigation Plugin -> Configuration`? Each of Collection / Single Type got such possibility.

**Comment by mikadev** [comment]
Yes of course it is because image is not a 'classic' relation with strapi  

In this exemple list is ok but image no and there is nothing related `Settings -> Navigation Plugin -> Configuration`
![image](https://user-images.githubusercontent.com/3314041/175264285-fd5dc26a-ca36-4b59-a824-d7c7744efd9c.png)

**Comment by cyp3rius** [comment]
Yep, seems thats a case. Registering the bug then to extend supported fields types.

**Comment by cyp3rius** [comment]
@ltsNotMike can you take a look?

**Comment by ltsNotMike** [comment]
I will try to make a fix asap 🙂

**Comment by GeoffreyPicard** [comment]
Have you any news about this subject ?

**Comment by cyp3rius** [comment]
Released as part of `v2.2.0`

**Comment by GeoffreyPicard** [comment]
Its not working for me.
Should we had something in the url of the REST API call ?
Can you had it in the documentation please ?

**Comment by ltsNotMike** [comment]
We implemented two options. One is to include `populate=field_name` in your query. The other one is fixing the lacking media fields on Settings Page. You can now set media to be populated every time through the Settings page.

**Comment by GeoffreyPicard** [comment]
It doesn't work for me.
See the exemple:

<img width="868" alt="Capture d’écran 2022-07-29 à 10 09 07" src="https://user-images.githubusercontent.com/20857213/181714469-6201b98e-bc50-46b7-9074-b2e9b843e1c1.png">

I cannot select the "image" field to populate

<img width="1050" alt="Capture d’écran 2022-07-29 à 10 10 00" src="https://user-images.githubusercontent.com/20857213/181714650-fa7a236a-86b2-40ff-b25a-fd30fea90758.png">

**Comment by ltsNotMike** [comment]
Are you sure that you are running version 2.2 of our plugin?

**Comment by GeoffreyPicard** [comment]
Yes i'm running with 2.2

First solution with populate= field_name work fine. 
I've to write it for every field 

Second solution still not working
<img width="1041" alt="Capture d’écran 2022-07-29 à 10 57 22" src="https://user-images.githubusercontent.com/20857213/181723517-253ea71b-fcf2-4326-aa07-baf37bee155a.png">

**Comment by ltsNotMike** [comment]
Have you tried rebuilding the project with `yarn build`? If that doesn't help, please try clearing .cache folder and building the project once again.

**Comment by GeoffreyPicard** [comment]
It work by doing a yarn build :) Thanks !
